#!/bin/bash
echo "🚀 Starting Prompt Visibility Dashboard..."
echo ""
echo "Commands: Available at http://localhost:3000"
echo "   - / : Dashboard (default)"
echo "   - /qwen : Qwen model"
echo "   - /mistral : Mistral model"
echo "   - /gemini : Gemini model"
echo "   - /openai : OpenAI model"
echo "   - /anthropic : Anthropic model"
echo ""
echo "API Endpoints:"
echo "   GET /api/data"
echo "   GET /api/statistical-summary"
echo "   GET /api/competitors"
echo "   GET /api/prompts"
echo "   GET /api/run-history"
echo ""
npm run dev
